name: cicd

#it runs manually whenever user needs
on:
  workflow_dispatch:
jobs:
 job1:
  runs_on: ubuntu-latest
   steps: 
     - name: code clone
       run: echo "clone done"
   
  job2:
   runs_on: ubuntu-latest
    steps:
    
   
      - name: code build
        run: echo "build done"
        

   job3:
    runs_on: ubuntu-latest
     steps:
      - name: code test
        run: echo "test run"
   
   job4:
    runs_on: ubuntu-latest
     steps:
   
      - name: code deploy
        run: echo "code deploy"
   
