name: DevSecOps pipeline

on:
    workflow_dispatch
    
jobs:

  # CI continous integration with security scanning
    code-quality:
      uses: ./.github/workflows/code-quality.yml

    secrets-scan:
      uses: ./.github/workflows/secrets-scan.yml

    Dependency-scan:
      uses: ./.github/workflows/dependency-scan.yml

    docker-scan:
      uses: ./.github/workflows/docker-lint.yml

      # build once the security scans are complete

    build:
      needs: [code-quality, secrets-scan, Dependency-scan, docker-scan]
      uses: ./.github/workflows/docker-build-push.yml
      secrets: inherit


    
