name: workflow
on:
 push:
   branches: [main]

jobs:
   job1:
     runs-on: ubuntu-22.04
     
     steps:
      - name: say to your username
        run: echo "hello dosto"
       
      - name: say to your username
        run: echo "hello $USER"

   job2:
     runs-on: ubuntu-22.04
     steps:
           - name: show me version of docker and python
             run: docker --version && python --version
       
